version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - bencodezen
  labels:
  - dependencies
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: cac
    versions:
    - 6.7.1
    - 6.7.2
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
